suppressMessages(suppressWarnings(library(plyr)))
library(tidyverse)
mut_sig <- read.table("mut_sig.tsv", header = TRUE, sep = "\t")
mut_sig_v3 <- data.frame(mut_sig)
mut_sig_v3 <- within(mut_sig_v3, Somatic.Mutation.Type <- reorder(Somatic.Mutation.Type, Signature.3))
saveRDS(mut_sig_v3, "mut_sig_ordered_by_sig3.rds")