---
title: "stat547-hw07-thibodeau-mylinh"
author: "My Linh Thibodeau"
date: '2017-11-11'
output: html_document:
	keep_md: true
---

For this homework, I will be using open access complete set of cancer somatic mutations from: 

Alexandrov, L. B. et al. Signatures of mutational processes in human cancer. 500, 415–421 (2013).

### Please note that I deliberately broke down each step of this homework in very small chunks/steps/scripts to make this material more "generalizable", which will allow me to use them for my research work as well.

***

This files will contain a narrative of homework 7 and some helpful notes regarding my process.

# Download the data

I started by using curl shell script in my Makefile to download the complete set of cancer somatic mutations:

```
mut_sig_raw.txt:
	curl -o mut_sig_raw.txt ftp://ftp.sanger.ac.uk/pub/cancer/AlexandrovEtAl/signatures.txt
```

I am also using my `mut_sig_clean.R` script to format the data. I performed that step to remove empty spaces from the column names because this would create problems with variable manipulation later.

# Perform exploratory analyses

Tasks:

* Bring the data in as data frame.
* Save a couple descriptive plots to file with highly informative names.
* Reorder the continents based on life expectancy. You decide the details.
* Sort the actual data in a deliberate fashion. You decide the details, but this should at least implement your new continent ordering.
* Write the Gapminder data to file(s), for immediate and future reuse.

**Please note that I did not complete the 5 tasks above in the order suggested because it made more sense to proceed in the order outlined below with my dataset ! **

(1) I am using my `mut_sig_tables.Rmd` script bring the mutational signatures in as a data frame. I am using the gather function of tidyverse to create a new dataframe table which will facilitate making plots later. I saved the output of this new data frame to mut_sig2.tsv.

(2) I am reordering the Somatic.Mutation.Type (e.g. A[C>A]A, A[C>A]C, etc.) according to their Signature.3 Score. 

(3) Sort the actual data in a deliberate fashion: Then I will order the Somatic.Mutation.Type according to ascending Signature.3 Score.

(4)  In this section, I am using the mut_sig_plot.Rmd script to create some plots, which I save in the subfolder called plots.

(5) Writing the mutational signatures input/output to files is performed (embedded) in the scripts mentioned above. 

# Perform statistical analyses

Tasks:

* Import the data created in the first script.
* Make sure your new continent order is still in force. You decide the details.
* Fit a linear regression of life expectancy on year within each country. Write the estimated intercepts, slopes, and residual error variance (or sd) to file. The R package broom may be useful here.
* Find the 3 or 4 “worst” and “best” countries for each continent. You decide the details.

As you know, I am using genomic data, so I have to adapt the tasks to my data, so here is what I did:

(1) I am importing and cleaning the data with my script read_clean_genome_text_files.R:

* reference mutation signatures (mut_sig.txt)
* somatic mutations for 5 types of cancer: ALL, AML, breast, medulloblastoma, pancreas

(2) The Somatic.Mutation.Type of the mut_sig.tsv (reference data) are still ordered according to Signature.3 values, as illustrated in Signature3_compare_plots.pdf

(3) Now we are changing gears a little bit. We are not looking at signatures of the reference somatic mutation (mut_sig.tsv) but we are looking at the Mutation.Type of 5 types of cancer: ALL, AML, breast, medulloblastoma, pancreas.

* We will be looking at the mean, median, standard deviation and count of each Mutation.Type in each dataset (we need the "gathered" versions of files for that step)
* We will write some stats tables (I peaked at how to make a loop [here](https://www.datacamp.com/community/tutorials/tutorial-on-loops-in-r), but ended up performing the task on individual dataset because I couldn't figure out how to avoid "overwriting" at each loop iteration). The summary statistics tables are available [here](statistics/)
* Then, we will (try to) look at linear regression. I have used this website [here](http://varianceexplained.org/r/broom-intro/) discussing broom and variance, and this website [here](https://cran.r-project.org/web/packages/broom/vignettes/broom.html) on some broom vignettes. And that's the moment I realized I didn't have two quantitative variables to perform linear regression modelling. This is a recurring problem with me: I always get into performing the analyses before making sure that the dataset format is appropriate (check this hw04 readme file [here](https://github.com/mylinhthibodeau/STAT545-HW-thibodeau-mylinh/tree/master/stat545-hw4-thibodeau-mylinh) if you want an example). So instead of fitting a linear regression of the lifeExp according to year, I will merge the cancer somatic data with the reference signature data, and I will fit a linear regression between Signature.3 and Signature.12 (see [here](http://cancer.sanger.ac.uk/cosmic/signatures) for more details on mutational signatures). 
* Find the 3 or 4 "worst" or "best" Signature.3 scores for each cancer_type.

# Generate figures

No worries here, I have generated plenty of figures. 

# Automate the pipeline

